from typing import Any, Optional, Union, Tuple, overload

class MatrixMixin:
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class CausalMatrix:
    def __init__(self, n: int, saveas: str = "", populate: bool = True, seed: Optional[int] = None) -> None: ...
    def get(self, i: int, j: int) -> bool: ...
    def set(self, i: int, j: int, value: bool) -> None: ...
    def size(self) -> int: ...
    def close(self) -> None: ...
    def multiply(self, other: 'CausalMatrix', result_file: str = "") -> 'IntegerMatrix': ...
    def elementwise_multiply(self, other: 'CausalMatrix', saveas: str = "") -> 'CausalMatrix': ...
    def __getitem__(self, key: Tuple[int, int]) -> bool: ...
    def __setitem__(self, key: Tuple[int, int], value: bool) -> None: ...
    def __mul__(self, other: 'CausalMatrix') -> 'CausalMatrix': ...
    @property
    def shape(self) -> Tuple[int, int]: ...
    @staticmethod
    def random(n: int, p: float = 0.5, seed: Optional[int] = None) -> 'CausalMatrix': ...

class IntegerMatrix:
    def __init__(self, n: int, backing_file: str = "") -> None: ...
    def get(self, i: int, j: int) -> int: ...
    def set(self, i: int, j: int, value: int) -> None: ...
    def size(self) -> int: ...
    def close(self) -> None: ...
    def __getitem__(self, key: Tuple[int, int]) -> int: ...
    @property
    def shape(self) -> Tuple[int, int]: ...

class TriangularFloatMatrix:
    def __init__(self, n: int, backing_file: str = "") -> None: ...
    def get(self, i: int, j: int) -> float: ...
    def set(self, i: int, j: int, value: float) -> None: ...
    def size(self) -> int: ...
    def close(self) -> None: ...
    def __getitem__(self, key: Tuple[int, int]) -> float: ...
    @property
    def shape(self) -> Tuple[int, int]: ...

class FloatMatrix:
    def __init__(self, n: int, backing_file: str = "") -> None: ...
    def get(self, i: int, j: int) -> float: ...
    def set(self, i: int, j: int, value: float) -> None: ...
    def size(self) -> int: ...
    def close(self) -> None: ...
    def __getitem__(self, key: Tuple[int, int]) -> float: ...
    @property
    def shape(self) -> Tuple[int, int]: ...

class Matrix:
    def __init__(self, data_or_n: Union[int, Any], populate: bool = True, saveas: str = "", seed: Optional[int] = None) -> None: ...
    def get(self, i: int, j: int) -> Any: ...
    def set(self, i: int, j: int, value: Any) -> None: ...
    def size(self) -> int: ...
    def close(self) -> None: ...
    def __getitem__(self, key: Tuple[int, int]) -> Any: ...
    def __setitem__(self, key: Tuple[int, int], value: Any) -> None: ...

class TriangularMatrix(Matrix): ...

def load(path: str) -> Union[CausalMatrix, IntegerMatrix, TriangularFloatMatrix, FloatMatrix]: ...

def compute_k(matrix: CausalMatrix, a: float, saveas: Optional[str] = None) -> FloatMatrix: ...

def matmul(a: Any, b: Any, saveas: Optional[str] = None) -> Any: ...

save: bool
seed: Optional[int]
