from typing import Any, Optional, Union, Tuple, overload
import os

class MatrixMixin:
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class MatrixBase:
    def __add__(self, other: 'MatrixBase') -> 'TriangularFloatMatrix': ...
    def __sub__(self, other: 'MatrixBase') -> 'TriangularFloatMatrix': ...
    def __mul__(self, other: Union['MatrixBase', float]) -> Union['TriangularFloatMatrix', 'MatrixBase']: ...
    def __rmul__(self, other: float) -> 'MatrixBase': ...

class TriangularBitMatrix(MatrixBase):
    def __init__(self, n: int, saveas: str = "") -> None: ...
    def get(self, i: int, j: int) -> bool: ...
    def set(self, i: int, j: int, value: bool) -> None: ...
    def size(self) -> int: ...
    def close(self) -> None: ...
    def get_backing_file(self) -> str: ...
    def multiply(self, other: 'TriangularBitMatrix', result_file: str = "") -> 'IntegerMatrix': ...
    def elementwise_multiply(self, other: 'TriangularBitMatrix', saveas: str = "") -> 'TriangularBitMatrix': ...
    def __getitem__(self, key: Tuple[int, int]) -> int: ...
    def __setitem__(self, key: Tuple[int, int], value: bool) -> None: ...
    @property
    def shape(self) -> Tuple[int, int]: ...
    @staticmethod
    def random(n: int, p: float = 0.5, seed: Optional[int] = None) -> 'TriangularBitMatrix': ...

def CausalMatrix(n: int, saveas: str = "") -> TriangularBitMatrix: ...

class IntegerMatrix(MatrixBase):
    def __init__(self, n: int, backing_file: str = "") -> None: ...
    def get(self, i: int, j: int) -> int: ...
    def set(self, i: int, j: int, value: int) -> None: ...
    def size(self) -> int: ...
    def close(self) -> None: ...
    def get_backing_file(self) -> str: ...
    def __getitem__(self, key: Tuple[int, int]) -> int: ...
    @property
    def shape(self) -> Tuple[int, int]: ...

class TriangularFloatMatrix(MatrixBase):
    def __init__(self, n: int, backing_file: str = "") -> None: ...
    def get(self, i: int, j: int) -> float: ...
    def set(self, i: int, j: int, value: float) -> None: ...
    def size(self) -> int: ...
    def close(self) -> None: ...
    def get_backing_file(self) -> str: ...
    def __getitem__(self, key: Tuple[int, int]) -> float: ...
    @property
    def shape(self) -> Tuple[int, int]: ...

class FloatMatrix(MatrixBase):
    def __init__(self, n: int, backing_file: str = "") -> None: ...
    def get(self, i: int, j: int) -> float: ...
    def set(self, i: int, j: int, value: float) -> None: ...

    def size(self) -> int: ...
    def close(self) -> None: ...
    def get_backing_file(self) -> str: ...
    def __getitem__(self, key: Tuple[int, int]) -> float: ...
    @property
    def shape(self) -> Tuple[int, int]: ...

class Matrix:
    def __init__(self, data_or_n: Union[int, Any], saveas: str = "") -> None: ...
    def get(self, i: int, j: int) -> Any: ...
    def set(self, i: int, j: int, value: Any) -> None: ...
    def size(self) -> int: ...
    def close(self) -> None: ...
    def get_backing_file(self) -> str: ...
    def __getitem__(self, key: Tuple[int, int]) -> Any: ...
    def __setitem__(self, key: Tuple[int, int], value: Any) -> None: ...

class TriangularMatrix(Matrix): ...

def load(path: str) -> Union[CausalMatrix, IntegerMatrix, TriangularFloatMatrix, FloatMatrix]: ...

def save(matrix: Any, path: Union[str, os.PathLike]) -> None: ...

def compute_k(matrix: CausalMatrix, a: float, saveas: Optional[str] = None) -> TriangularFloatMatrix: ...

def matmul(a: Any, b: Any, saveas: Optional[str] = None) -> Any: ...

keep_temp_files: bool
seed: Optional[int]
